package InterfaceAndAbstract;

// IMPLEMENTS & EXTEND CAN BE USED TOGETHER
// INTERFACE ARE ALWAYS PUBLIC AND IMPLEMENTED BY CLASS .
// INTERFACES ARE CATEGORIZED ONLY ON BASIS OF BEHAVIOURS (METHODS) .
// A CLASS CAN IMPLEMENTS MANY INTERFACES BUT CANNOT EXTEND MULTIPLE CLASSES (DIAMOND PROBLEM).
// CLASS THAT ARE IMPLEMENTING INTERFACE MUST HAVE DEFINED ALL METHODS OF INTERFACE.
// INTERFACES CAN N0T HAVE IT'S OWN OBJECT BUT CAN HAVE REFERENCE VARIABLE .
// OBJECT CREATION IS NOT ALLOWED FOR ABSTRACT CLASSES, SO IT DOES NOT HAVE ANY OBJECT
// ABSTRACTION CAN BE ACHIEVED BY INTERFACE .
// ABSTRACT CLASS IS JUST AN OVERVIEW OF AN ENTITY AND CAN BE IMPLEMENTED BY CHILD CLASS .
// ABSTRACT CLASS CAN HAVE ATTRIBUTES,METHODS AND ABSTRACT METHODS AS WELL , BUT THAT NEED TO DEFINED BY CHILD CLASS .
// ABSTRACT METHODS DON'T HAVE DEFINITION . CHILD CLASS WILL HAVE TO IMPLEMENTS ABSTRACT CLASS AND DEFINE ABSTRACT METHODS .
// ONE INTERFACE CAN EXTENDS MANY INTERFACES SEPERATED BY COMMA(,) AND CAN BE IMPLEMENTED BY OTHER CLASS

public class Main {
    public static void main(String[] args) {
        Peacock pk;
       Animal a = new Animal();
       a.run();
       a.fly();
       a.eat();
    }
}
